# Generated by Django 4.0.2 on 2022-02-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variation'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varaitions',
            field=models.ManyToManyField(blank=True, to='products.Variation'),
        ),
    ]
