# Generated by Django 4.0.2 on 2022-02-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_varaitions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varaitions',
            new_name='variations',
        ),
    ]
