# Generated by Django 4.0.2 on 2022-02-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_active_userprofile_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='active',
            new_name='is_active',
        ),
    ]
