# Generated by Django 4.0.2 on 2022-02-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
